### ISSUE TITLE
Phone gets hot pretty quickly

### ISSUE THREAD

**Issue by mickmister** [didier/phone-as-webcam#1]
Phone gets hot pretty quickly when running the webapp. The phone is not plugged into a computer. The phone is plugged into a charger though.

**Comment by didier** [comment]
@mickmister Constant camera (especially video) use is quite performance heavy and thus warms up some devices substantially, This is unfortunately not something that's within this project's control. Unplugging your charger will likely help, but other than that there isn't much I can do to help.
